[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pylint.messages_control]
disable = ["C0111"]

[tool.pylint.format]
max-line-length = 100

[tool.pylint.basic]
good-names = ["i", "n", "a", "b", "c"] 